theme = "soho"
baseurl = "/"
languageCode = "en"
title = "Tomás Capretto"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
summarylength = 10
enableEmoji = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
description = "PhD candidate, Statistics"
description2 = "IMASL (CONICET - UNSL)"

# gravatar = "soho@example.com"
profilePicture = "images/profile_pic.png"
copyright = "Tomás Capretto"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
  
  [[params.socialIcons]]
  icon = "fa-twitter"
  title = "Twitter"
  url = "https://twitter.com/CaprettoTomas"
  
  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/tomicapretto"
  
  [[params.socialIcons]]
  icon = "fa-stack-overflow"
  title = "Stack Overflow"
  url = "https://stackoverflow.com/users/12266277/tomas-capretto"
  
  [[params.socialIcons]]
  icon = "far fa-file-alt"
  title = "Curriculum Vitae"
  url = "https://github.com/tomicapretto/cv/raw/master/cv-english/cv-english.pdf"

[menu]

  [[menu.main]]
  name = "Posts"
  weight = 100
  identifier = "post"
  url = "/post/"
  
  [[menu.main]]
  name = "Projects"
  weight = 200
  identifier = "projects"
  url = "/projects/"
  
  [[menu.main]]
  name = "Slides"
  weight = 300
  identifier = "slides"
  url = "/slides/"

  [[menu.main]]
  name = "About"
  identifier = "about"
  weight = 400
  url = "/about/"

[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "monokai"
  tabWidth = 4
